services:
  backend:
    build: ./backend
    ports:
<<<<<<< HEAD
      - "5001:5000"
=======
      - "5001:5001"
>>>>>>> origin/Develop
    environment:
      PORT: 5001
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db 